<?php

declare(strict_types=1);

/*
 * PinterestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PinterestAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use PinterestAPILib\Models\AllBoards;

/**
 * Builder for model AllBoards
 *
 * @see AllBoards
 */
class AllBoardsBuilder
{
    /**
     * @var AllBoards
     */
    private $instance;

    private function __construct(AllBoards $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new all boards Builder object.
     */
    public static function init(array $items, string $bookmark): self
    {
        return new self(new AllBoards($items, $bookmark));
    }

    /**
     * Initializes a new all boards object.
     */
    public function build(): AllBoards
    {
        return CoreHelper::clone($this->instance);
    }
}
