<?php

declare(strict_types=1);

/*
 * PinterestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PinterestAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use PinterestAPILib\Models\BoardRequest;

/**
 * Builder for model BoardRequest
 *
 * @see BoardRequest
 */
class BoardRequestBuilder
{
    /**
     * @var BoardRequest
     */
    private $instance;

    private function __construct(BoardRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new board request Builder object.
     */
    public static function init(string $name, string $description, string $privacy): self
    {
        return new self(new BoardRequest($name, $description, $privacy));
    }

    /**
     * Initializes a new board request object.
     */
    public function build(): BoardRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
