<?php

declare(strict_types=1);

/*
 * PinterestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PinterestAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use PinterestAPILib\Models\Board;
use PinterestAPILib\Models\Owner;

/**
 * Builder for model Board
 *
 * @see Board
 */
class BoardBuilder
{
    /**
     * @var Board
     */
    private $instance;

    private function __construct(Board $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new board Builder object.
     */
    public static function init(string $id, string $name, string $description, Owner $owner, string $privacy): self
    {
        return new self(new Board($id, $name, $description, $owner, $privacy));
    }

    /**
     * Initializes a new board object.
     */
    public function build(): Board
    {
        return CoreHelper::clone($this->instance);
    }
}
