<?php

declare(strict_types=1);

/*
 * PinterestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PinterestAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use PinterestAPILib\Models\CreatePinResponse;
use PinterestAPILib\Models\Media;
use PinterestAPILib\Models\Owner;

/**
 * Builder for model CreatePinResponse
 *
 * @see CreatePinResponse
 */
class CreatePinResponseBuilder
{
    /**
     * @var CreatePinResponse
     */
    private $instance;

    private function __construct(CreatePinResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new create pin response Builder object.
     */
    public static function init(
        string $id,
        string $createdAt,
        string $link,
        string $title,
        string $description,
        string $dominantColor,
        string $altText,
        string $boardId,
        string $boardSectionId,
        Owner $boardOwner,
        Media $media,
        string $parentPinId
    ): self {
        return new self(new CreatePinResponse(
            $id,
            $createdAt,
            $link,
            $title,
            $description,
            $dominantColor,
            $altText,
            $boardId,
            $boardSectionId,
            $boardOwner,
            $media,
            $parentPinId
        ));
    }

    /**
     * Initializes a new create pin response object.
     */
    public function build(): CreatePinResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
