<?php

declare(strict_types=1);

/*
 * PinterestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PinterestAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use PinterestAPILib\Models\MediaSourceFile;

/**
 * Builder for model MediaSourceFile
 *
 * @see MediaSourceFile
 */
class MediaSourceFileBuilder
{
    /**
     * @var MediaSourceFile
     */
    private $instance;

    private function __construct(MediaSourceFile $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new media source file Builder object.
     */
    public static function init(string $url): self
    {
        return new self(new MediaSourceFile($url));
    }

    /**
     * Initializes a new media source file object.
     */
    public function build(): MediaSourceFile
    {
        return CoreHelper::clone($this->instance);
    }
}
