<?php

declare(strict_types=1);

/*
 * PinterestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PinterestAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use PinterestAPILib\Models\Media;

/**
 * Builder for model Media
 *
 * @see Media
 */
class MediaBuilder
{
    /**
     * @var Media
     */
    private $instance;

    private function __construct(Media $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new media Builder object.
     */
    public static function init(string $mediaType): self
    {
        return new self(new Media($mediaType));
    }

    /**
     * Initializes a new media object.
     */
    public function build(): Media
    {
        return CoreHelper::clone($this->instance);
    }
}
