<?php

declare(strict_types=1);

/*
 * PinterestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PinterestAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use PinterestAPILib\Models\Owner;

/**
 * Builder for model Owner
 *
 * @see Owner
 */
class OwnerBuilder
{
    /**
     * @var Owner
     */
    private $instance;

    private function __construct(Owner $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new owner Builder object.
     */
    public static function init(string $username): self
    {
        return new self(new Owner($username));
    }

    /**
     * Initializes a new owner object.
     */
    public function build(): Owner
    {
        return CoreHelper::clone($this->instance);
    }
}
