<?php

declare(strict_types=1);

/*
 * PinterestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PinterestAPILib\Controllers;

use Core\Request\Parameters\BodyParam;
use Core\Response\Types\ErrorType;
use CoreInterfaces\Core\Request\RequestMethod;
use PinterestAPILib\Exceptions\ApiException;
use PinterestAPILib\Models\AllBoards;
use PinterestAPILib\Models\Board;
use PinterestAPILib\Models\BoardRequest;

class BoardsController extends BaseController
{
    /**
     * Endpoint to create a new board
     *
     * @param BoardRequest $boardRequest name of the board
     *
     * @return Board Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function createBoard(BoardRequest $boardRequest): Board
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/boards')
            ->auth('global')
            ->parameters(BodyParam::init($boardRequest));

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('400', ErrorType::init('The board name is invalid or duplicate.'))
            ->type(Board::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * List all Pinterest boards
     *
     * @return AllBoards Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getAllBoards(): AllBoards
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::GET, '/boards')->auth('global');

        $_resHandler = $this->responseHandler()->type(AllBoards::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }
}
