<?php

declare(strict_types=1);

/*
 * PinterestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PinterestAPILib\Controllers;

use Core\Request\Parameters\BodyParam;
use Core\Response\Types\ErrorType;
use CoreInterfaces\Core\Request\RequestMethod;
use PinterestAPILib\Exceptions\ApiException;
use PinterestAPILib\Models\CreatePinResponse;
use PinterestAPILib\Models\NewPinRequest;

class PinsController extends BaseController
{
    /**
     * Create a new pin in Pinterest board.
     *
     * @param NewPinRequest $body
     *
     * @return CreatePinResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function createPin(NewPinRequest $body): CreatePinResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/pins')
            ->auth('global')
            ->parameters(BodyParam::init($body));

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('400', ErrorType::init('Invalid pin parameters'))
            ->throwErrorOn('403', ErrorType::init('The pin\'s image is too small, too large, or is broken'))
            ->throwErrorOn('404', ErrorType::init('Board or section not found'))
            ->throwErrorOn(
                '429',
                ErrorType::init('This request exceeded a rate limit. This can happen if a client exceeds one of' .
                ' the published rate limits or if multiple write operations are applied to an ob' .
                'ject within a short time window.')
            )
            ->type(CreatePinResponse::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }
}
