<?php

declare(strict_types=1);

/*
 * PinterestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PinterestAPILib\Models;

use stdClass;

/**
 * Model of type board that creates a new board.
 */
class Board implements \JsonSerializable
{
    /**
     * @var string
     */
    private $id;

    /**
     * @var string
     */
    private $name;

    /**
     * @var string
     */
    private $description;

    /**
     * @var Owner
     */
    private $owner;

    /**
     * @var string
     */
    private $privacy;

    /**
     * @param string $id
     * @param string $name
     * @param string $description
     * @param Owner $owner
     * @param string $privacy
     */
    public function __construct(string $id, string $name, string $description, Owner $owner, string $privacy)
    {
        $this->id = $id;
        $this->name = $name;
        $this->description = $description;
        $this->owner = $owner;
        $this->privacy = $privacy;
    }

    /**
     * Returns Id.
     * This is the board ID.
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * This is the board ID.
     *
     * @required
     * @maps id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Name.
     * This is the name of the board.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * This is the name of the board.
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Description.
     * Describe what the board is about.
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * Describe what the board is about.
     *
     * @required
     * @maps description
     */
    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Owner.
     * State who the owner of the board is.
     */
    public function getOwner(): Owner
    {
        return $this->owner;
    }

    /**
     * Sets Owner.
     * State who the owner of the board is.
     *
     * @required
     * @maps owner
     */
    public function setOwner(Owner $owner): void
    {
        $this->owner = $owner;
    }

    /**
     * Returns Privacy.
     * Set privacy setting of the board.
     */
    public function getPrivacy(): string
    {
        return $this->privacy;
    }

    /**
     * Sets Privacy.
     * Set privacy setting of the board.
     *
     * @required
     * @maps privacy
     */
    public function setPrivacy(string $privacy): void
    {
        $this->privacy = $privacy;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id']          = $this->id;
        $json['name']        = $this->name;
        $json['description'] = $this->description;
        $json['owner']       = $this->owner;
        $json['privacy']     = $this->privacy;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
