<?php

declare(strict_types=1);

/*
 * PinterestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PinterestAPILib\Models;

use stdClass;

class CreatePinResponse implements \JsonSerializable
{
    /**
     * @var string
     */
    private $id;

    /**
     * @var string
     */
    private $createdAt;

    /**
     * @var string
     */
    private $link;

    /**
     * @var string
     */
    private $title;

    /**
     * @var string
     */
    private $description;

    /**
     * @var string
     */
    private $dominantColor;

    /**
     * @var string
     */
    private $altText;

    /**
     * @var string
     */
    private $boardId;

    /**
     * @var string
     */
    private $boardSectionId;

    /**
     * @var Owner
     */
    private $boardOwner;

    /**
     * @var Media
     */
    private $media;

    /**
     * @var string
     */
    private $parentPinId;

    /**
     * @param string $id
     * @param string $createdAt
     * @param string $link
     * @param string $title
     * @param string $description
     * @param string $dominantColor
     * @param string $altText
     * @param string $boardId
     * @param string $boardSectionId
     * @param Owner $boardOwner
     * @param Media $media
     * @param string $parentPinId
     */
    public function __construct(
        string $id,
        string $createdAt,
        string $link,
        string $title,
        string $description,
        string $dominantColor,
        string $altText,
        string $boardId,
        string $boardSectionId,
        Owner $boardOwner,
        Media $media,
        string $parentPinId
    ) {
        $this->id = $id;
        $this->createdAt = $createdAt;
        $this->link = $link;
        $this->title = $title;
        $this->description = $description;
        $this->dominantColor = $dominantColor;
        $this->altText = $altText;
        $this->boardId = $boardId;
        $this->boardSectionId = $boardSectionId;
        $this->boardOwner = $boardOwner;
        $this->media = $media;
        $this->parentPinId = $parentPinId;
    }

    /**
     * Returns Id.
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @required
     * @maps id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Created At.
     */
    public function getCreatedAt(): string
    {
        return $this->createdAt;
    }

    /**
     * Sets Created At.
     *
     * @required
     * @maps created_at
     */
    public function setCreatedAt(string $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Returns Link.
     */
    public function getLink(): string
    {
        return $this->link;
    }

    /**
     * Sets Link.
     *
     * @required
     * @maps link
     */
    public function setLink(string $link): void
    {
        $this->link = $link;
    }

    /**
     * Returns Title.
     */
    public function getTitle(): string
    {
        return $this->title;
    }

    /**
     * Sets Title.
     *
     * @required
     * @maps title
     */
    public function setTitle(string $title): void
    {
        $this->title = $title;
    }

    /**
     * Returns Description.
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     *
     * @required
     * @maps description
     */
    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Dominant Color.
     */
    public function getDominantColor(): string
    {
        return $this->dominantColor;
    }

    /**
     * Sets Dominant Color.
     *
     * @required
     * @maps dominant_color
     */
    public function setDominantColor(string $dominantColor): void
    {
        $this->dominantColor = $dominantColor;
    }

    /**
     * Returns Alt Text.
     */
    public function getAltText(): string
    {
        return $this->altText;
    }

    /**
     * Sets Alt Text.
     *
     * @required
     * @maps alt_text
     */
    public function setAltText(string $altText): void
    {
        $this->altText = $altText;
    }

    /**
     * Returns Board Id.
     */
    public function getBoardId(): string
    {
        return $this->boardId;
    }

    /**
     * Sets Board Id.
     *
     * @required
     * @maps board_id
     */
    public function setBoardId(string $boardId): void
    {
        $this->boardId = $boardId;
    }

    /**
     * Returns Board Section Id.
     */
    public function getBoardSectionId(): string
    {
        return $this->boardSectionId;
    }

    /**
     * Sets Board Section Id.
     *
     * @required
     * @maps board_section_id
     */
    public function setBoardSectionId(string $boardSectionId): void
    {
        $this->boardSectionId = $boardSectionId;
    }

    /**
     * Returns Board Owner.
     */
    public function getBoardOwner(): Owner
    {
        return $this->boardOwner;
    }

    /**
     * Sets Board Owner.
     *
     * @required
     * @maps board_owner
     */
    public function setBoardOwner(Owner $boardOwner): void
    {
        $this->boardOwner = $boardOwner;
    }

    /**
     * Returns Media.
     */
    public function getMedia(): Media
    {
        return $this->media;
    }

    /**
     * Sets Media.
     *
     * @required
     * @maps media
     */
    public function setMedia(Media $media): void
    {
        $this->media = $media;
    }

    /**
     * Returns Parent Pin Id.
     */
    public function getParentPinId(): string
    {
        return $this->parentPinId;
    }

    /**
     * Sets Parent Pin Id.
     *
     * @required
     * @maps parent_pin_id
     */
    public function setParentPinId(string $parentPinId): void
    {
        $this->parentPinId = $parentPinId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id']               = $this->id;
        $json['created_at']       = $this->createdAt;
        $json['link']             = $this->link;
        $json['title']            = $this->title;
        $json['description']      = $this->description;
        $json['dominant_color']   = $this->dominantColor;
        $json['alt_text']         = $this->altText;
        $json['board_id']         = $this->boardId;
        $json['board_section_id'] = $this->boardSectionId;
        $json['board_owner']      = $this->boardOwner;
        $json['media']            = $this->media;
        $json['parent_pin_id']    = $this->parentPinId;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
