<?php

declare(strict_types=1);

/*
 * PinterestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PinterestAPILib\Models;

use stdClass;

/**
 * Type to define media input.
 */
class MediaSourceFile implements \JsonSerializable
{
    /**
     * @var string
     */
    private $sourceType;

    /**
     * @var string
     */
    private $url;

    /**
     * @param string $url
     */
    public function __construct(string $url)
    {
        $this->url = $url;
    }

    /**
     * Returns Source Type.
     * States the type of the media input.
     */
    public function getSourceType(): string
    {
        return $this->sourceType;
    }

    /**
     * Sets Source Type.
     * States the type of the media input.
     *
     * @maps source_type
     */
    public function setSourceType(string $sourceType): void
    {
        $this->sourceType = $sourceType;
    }

    /**
     * Returns Url.
     * This is the URL of the media.
     */
    public function getUrl(): string
    {
        return $this->url;
    }

    /**
     * Sets Url.
     * This is the URL of the media.
     *
     * @required
     * @maps url
     */
    public function setUrl(string $url): void
    {
        $this->url = $url;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['source_type'] = $this->sourceType;
        $json['url']         = $this->url;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
