<?php

declare(strict_types=1);

/*
 * PinterestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PinterestAPILib\Models;

use stdClass;

class Media implements \JsonSerializable
{
    /**
     * @var string
     */
    private $mediaType;

    /**
     * @param string $mediaType
     */
    public function __construct(string $mediaType)
    {
        $this->mediaType = $mediaType;
    }

    /**
     * Returns Media Type.
     */
    public function getMediaType(): string
    {
        return $this->mediaType;
    }

    /**
     * Sets Media Type.
     *
     * @required
     * @maps media_type
     */
    public function setMediaType(string $mediaType): void
    {
        $this->mediaType = $mediaType;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['media_type'] = $this->mediaType;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
