<?php

declare(strict_types=1);

/*
 * PinterestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PinterestAPILib\Models;

use stdClass;

class NewPinRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $link;

    /**
     * @var string|null
     */
    private $title;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var string|null
     */
    private $dominantColor;

    /**
     * @var string|null
     */
    private $altText;

    /**
     * @var string
     */
    private $boardId;

    /**
     * @var string|null
     */
    private $boardSectionId;

    /**
     * @var MediaSourceFile
     */
    private $mediaSource;

    /**
     * @var string|null
     */
    private $parentPinId;

    /**
     * @param string $boardId
     * @param MediaSourceFile $mediaSource
     */
    public function __construct(string $boardId, MediaSourceFile $mediaSource)
    {
        $this->boardId = $boardId;
        $this->mediaSource = $mediaSource;
    }

    /**
     * Returns Link.
     */
    public function getLink(): ?string
    {
        return $this->link;
    }

    /**
     * Sets Link.
     *
     * @maps link
     */
    public function setLink(?string $link): void
    {
        $this->link = $link;
    }

    /**
     * Returns Title.
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * Sets Title.
     *
     * @maps title
     */
    public function setTitle(?string $title): void
    {
        $this->title = $title;
    }

    /**
     * Returns Description.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Dominant Color.
     */
    public function getDominantColor(): ?string
    {
        return $this->dominantColor;
    }

    /**
     * Sets Dominant Color.
     *
     * @maps dominant_color
     */
    public function setDominantColor(?string $dominantColor): void
    {
        $this->dominantColor = $dominantColor;
    }

    /**
     * Returns Alt Text.
     */
    public function getAltText(): ?string
    {
        return $this->altText;
    }

    /**
     * Sets Alt Text.
     *
     * @maps alt_text
     */
    public function setAltText(?string $altText): void
    {
        $this->altText = $altText;
    }

    /**
     * Returns Board Id.
     */
    public function getBoardId(): string
    {
        return $this->boardId;
    }

    /**
     * Sets Board Id.
     *
     * @required
     * @maps board_id
     */
    public function setBoardId(string $boardId): void
    {
        $this->boardId = $boardId;
    }

    /**
     * Returns Board Section Id.
     */
    public function getBoardSectionId(): ?string
    {
        return $this->boardSectionId;
    }

    /**
     * Sets Board Section Id.
     *
     * @maps board_section_id
     */
    public function setBoardSectionId(?string $boardSectionId): void
    {
        $this->boardSectionId = $boardSectionId;
    }

    /**
     * Returns Media Source.
     */
    public function getMediaSource(): MediaSourceFile
    {
        return $this->mediaSource;
    }

    /**
     * Sets Media Source.
     *
     * @required
     * @maps media_source
     */
    public function setMediaSource(MediaSourceFile $mediaSource): void
    {
        $this->mediaSource = $mediaSource;
    }

    /**
     * Returns Parent Pin Id.
     */
    public function getParentPinId(): ?string
    {
        return $this->parentPinId;
    }

    /**
     * Sets Parent Pin Id.
     *
     * @maps parent_pin_id
     */
    public function setParentPinId(?string $parentPinId): void
    {
        $this->parentPinId = $parentPinId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->link)) {
            $json['link']             = $this->link;
        }
        if (isset($this->title)) {
            $json['title']            = $this->title;
        }
        if (isset($this->description)) {
            $json['description']      = $this->description;
        }
        if (isset($this->dominantColor)) {
            $json['dominant_color']   = $this->dominantColor;
        }
        if (isset($this->altText)) {
            $json['alt_text']         = $this->altText;
        }
        $json['board_id']             = $this->boardId;
        if (isset($this->boardSectionId)) {
            $json['board_section_id'] = $this->boardSectionId;
        }
        $json['media_source']         = $this->mediaSource;
        if (isset($this->parentPinId)) {
            $json['parent_pin_id']    = $this->parentPinId;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
