<?php

declare(strict_types=1);

/*
 * PinterestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PinterestAPILib\Models;

use stdClass;

/**
 * Model to create an endpoint of type owner.
 */
class Owner implements \JsonSerializable
{
    /**
     * @var string
     */
    private $username;

    /**
     * @param string $username
     */
    public function __construct(string $username)
    {
        $this->username = $username;
    }

    /**
     * Returns Username.
     * States the name of the board owner.
     */
    public function getUsername(): string
    {
        return $this->username;
    }

    /**
     * Sets Username.
     * States the name of the board owner.
     *
     * @required
     * @maps username
     */
    public function setUsername(string $username): void
    {
        $this->username = $username;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['username'] = $this->username;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
