<?php

declare(strict_types=1);

/*
 * PinterestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PinterestAPILib;

use Core\ClientBuilder;
use Core\Utils\CoreHelper;
use PinterestAPILib\Controllers\BoardsController;
use PinterestAPILib\Controllers\OAuthAuthorizationController;
use PinterestAPILib\Controllers\PinsController;
use PinterestAPILib\Utils\CompatibilityConverter;
use Unirest\Configuration;
use Unirest\HttpClient;

class PinterestAPIClient implements ConfigurationInterface
{
    private $pins;

    private $boards;

    private $oAuthAuthorization;

    private $authorizationCodeAuthManager;

    private $config;

    private $client;

    /**
     * @see PinterestAPIClientBuilder::init()
     * @see PinterestAPIClientBuilder::build()
     *
     * @param array $config
     */
    public function __construct(array $config = [])
    {
        $this->config = array_merge(ConfigurationDefaults::_ALL, CoreHelper::clone($config));
        $this->authorizationCodeAuthManager = new AuthorizationCodeAuthManager(
            $this->config['oAuthClientId'] ?? ConfigurationDefaults::O_AUTH_CLIENT_ID,
            $this->config['oAuthClientSecret'] ?? ConfigurationDefaults::O_AUTH_CLIENT_SECRET,
            $this->config['oAuthRedirectUri'] ?? ConfigurationDefaults::O_AUTH_REDIRECT_URI,
            $this->config['oAuthToken'],
            $this->config['oAuthScopes']
        );
        $this->validateConfig();
        $this->client = ClientBuilder::init(new HttpClient(Configuration::init($this)))
            ->converter(new CompatibilityConverter())
            ->jsonHelper(ApiHelper::getJsonHelper())
            ->apiCallback($this->config['httpCallback'] ?? null)
            ->userAgent('APIMATIC 3.0')
            ->serverUrls(self::ENVIRONMENT_MAP[$this->getEnvironment()], Server::DEFAULT_)
            ->authManagers(['global' => $this->authorizationCodeAuthManager])
            ->build();
        $this->authorizationCodeAuthManager->setClient($this->client);
    }

    /**
     * Create a builder with the current client's configurations.
     *
     * @return PinterestAPIClientBuilder PinterestAPIClientBuilder instance
     */
    public function toBuilder(): PinterestAPIClientBuilder
    {
        return PinterestAPIClientBuilder::init()
            ->timeout($this->getTimeout())
            ->enableRetries($this->shouldEnableRetries())
            ->numberOfRetries($this->getNumberOfRetries())
            ->retryInterval($this->getRetryInterval())
            ->backOffFactor($this->getBackOffFactor())
            ->maximumRetryWaitTime($this->getMaximumRetryWaitTime())
            ->retryOnTimeout($this->shouldRetryOnTimeout())
            ->httpStatusCodesToRetry($this->getHttpStatusCodesToRetry())
            ->httpMethodsToRetry($this->getHttpMethodsToRetry())
            ->environment($this->getEnvironment())
            ->oAuthClientId($this->authorizationCodeAuthManager->getOAuthClientId())
            ->oAuthClientSecret($this->authorizationCodeAuthManager->getOAuthClientSecret())
            ->oAuthRedirectUri($this->authorizationCodeAuthManager->getOAuthRedirectUri())
            ->oAuthToken($this->authorizationCodeAuthManager->getOAuthToken())
            ->oAuthScopes($this->authorizationCodeAuthManager->getOAuthScopes())
            ->httpCallback($this->config['httpCallback'] ?? null);
    }

    public function getTimeout(): int
    {
        return $this->config['timeout'] ?? ConfigurationDefaults::TIMEOUT;
    }

    public function shouldEnableRetries(): bool
    {
        return $this->config['enableRetries'] ?? ConfigurationDefaults::ENABLE_RETRIES;
    }

    public function getNumberOfRetries(): int
    {
        return $this->config['numberOfRetries'] ?? ConfigurationDefaults::NUMBER_OF_RETRIES;
    }

    public function getRetryInterval(): float
    {
        return $this->config['retryInterval'] ?? ConfigurationDefaults::RETRY_INTERVAL;
    }

    public function getBackOffFactor(): float
    {
        return $this->config['backOffFactor'] ?? ConfigurationDefaults::BACK_OFF_FACTOR;
    }

    public function getMaximumRetryWaitTime(): int
    {
        return $this->config['maximumRetryWaitTime'] ?? ConfigurationDefaults::MAXIMUM_RETRY_WAIT_TIME;
    }

    public function shouldRetryOnTimeout(): bool
    {
        return $this->config['retryOnTimeout'] ?? ConfigurationDefaults::RETRY_ON_TIMEOUT;
    }

    public function getHttpStatusCodesToRetry(): array
    {
        return $this->config['httpStatusCodesToRetry'] ?? ConfigurationDefaults::HTTP_STATUS_CODES_TO_RETRY;
    }

    public function getHttpMethodsToRetry(): array
    {
        return $this->config['httpMethodsToRetry'] ?? ConfigurationDefaults::HTTP_METHODS_TO_RETRY;
    }

    public function getEnvironment(): string
    {
        return $this->config['environment'] ?? ConfigurationDefaults::ENVIRONMENT;
    }

    public function getAuthorizationCodeAuth(): ?AuthorizationCodeAuth
    {
        return $this->authorizationCodeAuthManager;
    }

    /**
     * Get the client configuration as an associative array
     *
     * @see PinterestAPIClientBuilder::getConfiguration()
     */
    public function getConfiguration(): array
    {
        return $this->toBuilder()->getConfiguration();
    }

    /**
     * Clone this client and override given configuration options
     *
     * @see PinterestAPIClientBuilder::build()
     */
    public function withConfiguration(array $config): self
    {
        return new self(array_merge($this->config, $config));
    }

    /**
     * Validate required configuration variables
     */
    private function validateConfig(): void
    {
        PinterestAPIClientBuilder::init()->oAuthScopes($this->authorizationCodeAuthManager->getOAuthScopes());
    }

    /**
     * Get the base uri for a given server in the current environment.
     *
     * @param string $server Server name
     *
     * @return string Base URI
     */
    public function getBaseUri(string $server = Server::DEFAULT_): string
    {
        return $this->client->getGlobalRequest($server)->getQueryUrl();
    }

    /**
     * Returns Pins Controller
     */
    public function getPinsController(): PinsController
    {
        if ($this->pins == null) {
            $this->pins = new PinsController($this->client);
        }
        return $this->pins;
    }

    /**
     * Returns Boards Controller
     */
    public function getBoardsController(): BoardsController
    {
        if ($this->boards == null) {
            $this->boards = new BoardsController($this->client);
        }
        return $this->boards;
    }

    /**
     * Returns O Auth Authorization Controller
     */
    public function getOAuthAuthorizationController(): OAuthAuthorizationController
    {
        if ($this->oAuthAuthorization == null) {
            $this->oAuthAuthorization = new OAuthAuthorizationController($this->client);
        }
        return $this->oAuthAuthorization;
    }

    /**
     * A map of all base urls used in different environments and servers
     *
     * @var array
     */
    private const ENVIRONMENT_MAP = [
        Environment::PRODUCTION => [
            Server::DEFAULT_ => 'https://api.pinterest.com/v5',
            Server::AUTHSERVER => 'https://www.pinterest.com/oauth'
        ]
    ];
}
